<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[actual & expected maching Tc is passed]]>
    </line>
    <line>
      <![CDATA[Sorry TC is failed =  validateUsername]]>
    </line>
  </reporter-output>
  <suite started-at="2022-07-09T17:12:35 IST" name="Default suite" finished-at="2022-07-09T17:13:20 IST" duration-ms="45057">
    <groups>
    </groups>
    <test started-at="2022-07-09T17:12:35 IST" name="Default test" finished-at="2022-07-09T17:13:20 IST" duration-ms="45057">
      <class name="Kite_TestNG_Listeners.Validate_kite_UserId">
        <test-method is-config="true" signature="LaunchBrowser()[pri:0, instance:Kite_TestNG_Listeners.Validate_kite_UserId@59505b48]" started-at="2022-07-09T17:12:35 IST" name="LaunchBrowser" finished-at="2022-07-09T17:13:12 IST" duration-ms="36806" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method is-config="true" signature="loginToKiteapp()[pri:0, instance:Kite_TestNG_Listeners.Validate_kite_UserId@59505b48]" started-at="2022-07-09T17:13:12 IST" name="loginToKiteapp" finished-at="2022-07-09T17:13:14 IST" duration-ms="2206" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToKiteapp -->
        <test-method signature="validateUsername()[pri:0, instance:Kite_TestNG_Listeners.Validate_kite_UserId@59505b48]" started-at="2022-07-09T17:13:14 IST" name="validateUsername" finished-at="2022-07-09T17:13:17 IST" duration-ms="3253" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at Kite_TestNG_Listeners.Validate_kite_UserId.validateUsername(Validate_kite_UserId.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[actual & expected maching Tc is passed]]>
            </line>
            <line>
              <![CDATA[Sorry TC is failed =  validateUsername]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateUsername -->
        <test-method is-config="true" signature="logoutKiteapp()[pri:0, instance:Kite_TestNG_Listeners.Validate_kite_UserId@59505b48]" started-at="2022-07-09T17:13:18 IST" name="logoutKiteapp" finished-at="2022-07-09T17:13:19 IST" duration-ms="1734" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutKiteapp -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Kite_TestNG_Listeners.Validate_kite_UserId@59505b48]" started-at="2022-07-09T17:13:19 IST" name="closeBrowser" finished-at="2022-07-09T17:13:20 IST" duration-ms="570" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Kite_TestNG_Listeners.Validate_kite_UserId -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
